[tools]
actionlint = "1.7.9"
age = "1.2.1"
chezmoi = "2.67.0"
cosign = "3.0.2"
go = "1.25.5"
golangci-lint = "2.7.1"
"npm:markdownlint-cli" = "0.46.0"
pnpm = "10.24.0"
ruby = "3.4.7"
shellcheck = "0.11.0"
task = "3.45.4"
tflint = "0.60.0"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]
